name: Run Playwright Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install --with-deps
    - name: Lint with flake8
      run: |
        make linter
    - name: Test with pytest
      run: |
        make test
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1.8
      with:
      allure_results: allure-results
      report_path: allure-report
      upload_artifact: true
      gh_pages: false
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
#jobs:
#  test:
#    name: ğŸ§ª Run Pytest with Playwright + Allure
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: â¬‡ï¸ Checkout code
#        uses: actions/checkout@v4
#
#      - name: ğŸ Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.11'
#
#      - name: ğŸ“¦ Install dependencies
#        run: |
#          python -m venv venv
#          source venv/bin/activate
#          pip install -r requirements.txt
#          playwright install --with-deps
#
#      - name: âœ… Run tests with pytest
#        run: |
#          source venv/bin/activate
#          pytest --alluredir=allure-results
#
#      - name: ğŸ“Š Generate Allure Report
#        uses: simple-elf/allure-report-action@v1.8
#        with:
#          allure_results: allure-results
#          report_path: allure-report
#          upload_artifact: true
#          gh_pages: false
